version: "2.0"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - logvolume01:/var/log
    environment:
      - IPFS_HOST=ipfs
      - "FLASK_HOST=0.0.0.0"
      - UNLOCK=foo
    links:
      - ipfs
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs
volumes:
  logvolume01: {}

